# Generated by Django 2.1.5 on 2019-02-04 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0005_departmentsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_like', models.BooleanField()),
                ('f_grade', models.CharField(max_length=60)),
                ('f_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actions.QuestionsModel')),
                ('f_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'answers',
            },
        ),
    ]
