# Generated by Django 2.1.5 on 2019-02-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20190207_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answersmodel',
            options={'ordering': ['id']},
        ),
    ]
