version: '3'

services:
  db:
    image: holyshining/techpoll:techpoll
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'techpoll'
  web:
    image: holyshining/techpoll:django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db