# Generated by Django 2.1.5 on 2019-02-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_stagesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagesmodel',
            old_name='title',
            new_name='name',
        ),
    ]
