# Generated by Django 2.1.5 on 2019-02-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20190202_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None, max_length=255)),
                ('hint', models.TextField(default=None, max_length=300)),
                ('f_stage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='actions.StagesModel')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
