# Generated by Django 2.1.5 on 2019-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_questionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('questions', models.ManyToManyField(to='actions.QuestionsModel')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
