# Generated by Django 2.1.5 on 2019-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190202_1518'),
        ('actions', '0005_departmentsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsmodel',
            name='users',
            field=models.ManyToManyField(to='authentication.UserData'),
        ),
    ]
