# Generated by Django 2.1.5 on 2019-02-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_gradesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentsmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='gradesmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='questionsmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sectionsmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stagesmodel',
            options={'ordering': ['id']},
        ),
    ]
