# Generated by Django 2.1.5 on 2019-02-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_auto_20190207_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionsmodel',
            options={'ordering': ['name']},
        ),
    ]
