# Generated by Django 2.1.5 on 2019-01-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190131_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='uniquePass',
        ),
    ]
