# Generated by Django 2.1.5 on 2019-02-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userdata_uniquepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='encryptedPass',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
