# Generated by Django 2.1.5 on 2019-02-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userdata_encryptedpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeName', models.CharField(default='null', max_length=60)),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='null', max_length=60)),
                ('Permissions', models.ManyToManyField(to='authentication.PermissionsModel')),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
    ]
