# Generated by Django 2.1.5 on 2019-02-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_permissionsmodel_rolesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='fRole',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.RolesModel'),
        ),
    ]
