# Generated by Django 2.1.5 on 2019-02-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0008_auto_20190201_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fRole',
            new_name='f_role',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='fAuth',
        ),
        migrations.AddField(
            model_name='userdata',
            name='f_auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
