# Generated by Django 2.1.5 on 2019-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190202_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='permissionsmodel',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
        migrations.AlterField(
            model_name='permissionsmodel',
            name='code_name',
            field=models.CharField(default='No codename', max_length=100),
        ),
    ]
