# Generated by Django 2.1.5 on 2019-02-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190207_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rolesmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'ordering': ['name', 'surname', 'id']},
        ),
    ]
