# Generated by Django 2.1.5 on 2019-02-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20190207_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionsmodel',
            name='name',
            field=models.CharField(default='No name', max_length=255),
        ),
    ]
